// <auto-generated />
using System;
using BeautyManager.Shared.Connection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeautyManager.Shared.Migrations
{
    [DbContext(typeof(BeautyDbContext))]
    [Migration("20251015204101_seedData")]
    partial class seedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BeautyManager.Shared.Models.Db.BeautyBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("ExecutingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("BeautyBooks");
                });

            modelBuilder.Entity("BeautyManager.Shared.Models.Local.BeautyTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("TaskDuration")
                        .HasColumnType("time(6)");

                    b.Property<string>("TaskTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("BeautyTask");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TaskDuration = new TimeOnly(1, 0, 0),
                            TaskTitle = "Man haircut"
                        },
                        new
                        {
                            Id = 2,
                            TaskDuration = new TimeOnly(1, 30, 0),
                            TaskTitle = "Man haircut + beard"
                        },
                        new
                        {
                            Id = 3,
                            TaskDuration = new TimeOnly(0, 30, 0),
                            TaskTitle = "Man beard"
                        },
                        new
                        {
                            Id = 4,
                            TaskDuration = new TimeOnly(1, 30, 0),
                            TaskTitle = "Woman haircut"
                        },
                        new
                        {
                            Id = 5,
                            TaskDuration = new TimeOnly(2, 0, 0),
                            TaskTitle = "Woman haircut + hair wash"
                        });
                });

            modelBuilder.Entity("BeautyManager.Shared.Models.Db.BeautyBook", b =>
                {
                    b.HasOne("BeautyManager.Shared.Models.Local.BeautyTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });
#pragma warning restore 612, 618
        }
    }
}
